# Generated by Django 4.0.6 on 2022-07-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('Age', models.IntegerField(null=True)),
                ('Location', models.CharField(max_length=50, null=True)),
                ('Occupation', models.CharField(blank=True, max_length=20, null=True)),
                ('Uploded_by', models.CharField(blank=True, max_length=50, null=True)),
                ('Uploded_on', models.TimeField(auto_now_add=True, null=True)),
                ('No_of_download', models.IntegerField(null=True)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
            ],
        ),
    ]
